2025-02-24 18:39:15,526 ERROR: Exception on /user/Olga [GET] [in C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\app\routes.py", line 73, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Olga\PycharmProjects\Flask_book\app\templates\user.html", line 28, in template
    {{ form.submit(value='Unfollow' }}
    ^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2025-02-24 18:44:26,518 ERROR: Exception on /user/Olga [GET] [in C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\app\routes.py", line 73, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Olga\PycharmProjects\Flask_book\app\templates\user.html", line 28, in template
    {{ form.submit(value='Unfollow' }}
    ^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2025-02-24 18:45:48,807 INFO: My project [in C:\Users\Olga\PycharmProjects\Flask_book\app\__init__.py:41]
2025-02-24 18:46:07,197 INFO: My project [in C:\Users\Olga\PycharmProjects\Flask_book\app\__init__.py:41]
2025-02-24 18:46:21,066 ERROR: Exception on /edit_profile [GET] [in C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Olga\PycharmProjects\Flask_book\app\routes.py", line 84, in edit_profile
    form = EditProfileForm()
  File "C:\Users\Olga\PycharmProjects\Flask_book\.venv\Lib\site-packages\wtforms\form.py", line 209, in __call__
    return type.__call__(cls, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: EditProfileForm.__init__() missing 1 required positional argument: 'original_username'
2025-02-28 13:18:06,707 INFO: My project [in C:\Users\Olga\PycharmProjects\Flask_book\app\__init__.py:41]
